spring:
  application:
    name: ecommerce-mcp-demo
  
  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce_demo
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  
  ai:
    openai:
      api-key: ${OPENAI_API_KEY:your-api-key-here}
      base-url: https://api.openai.com
      chat:
        options:
          model: gpt-3.5-turbo
          temperature: 0.7

server:
  port: 8080

logging:
  level:
    com.example.ecommerce: DEBUG
    org.springframework.ai: DEBUG
